export const types = Object.freeze({
    USER_START_FETCHING: 'USER_START_FETCHING',
    USER_STOP_FETCHING: 'USER_STOP_FETCHING',
    USER_SET_FETCHING_ERROR: 'USER_SET_FETCHING_ERROR',

    USER_NEW_USER: 'USER_NEW_USER',
    USER_LOGIN: 'USER_LOGIN',
    USER_VIEW: 'USER_VIEW',
    USER_UPDATE: 'USER_UPDATE',
    USER_LOGOUT: 'USER_LOGOUT',
})